#! /bin/sh

sxhkd &
polybar top &
polybar bottom &

bspc monitor -d term web code music chat ws1 ws2 ws3

bspc config focus_follows_pointer true

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color  "#E5E9F0"
bspc config focused_border_color  "#88C0D0"


#doesn't work:
#floating_apps=( "pcmanfm" "mpv" "gpicview" "feh" "galculator" )
#for i in "${floating_apps[@]}";
#do
#  bspc rule -a $i state=floating
#done

# windows that go to specific desktops
bspc rule -a Atom desktop=code follow=on
bspc rule -a Gimp desktop=code state=floating follow=on
bspc rule -a Inkscape desktop=code follow=on
bspc rule -a Firefox desktop=web follow=on
bspc rule -a Google-chrome desktop=web follow=on

# windows that can float on any desktop
bspc rule -a Pcmanfm state=floating
bspc rule -a mousepad state=floating
bspc rule -a mpv state=floating
bspc rule -a 'Image Viewer' state=floating
bspc rule -a feh state=floating
bspc rule -a galculator state=floating

bspc rule -a Steam desktop=ws1 state=floating follow=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
